# Your Solution
version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: books_inventory_user
      POSTGRES_PASSWORD: 9hNFJrnxrxlTVYcGkiVFuBEhvu5hFNoh
      POSTGRES_DB: books_inventory
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

  book_catalog:
    image: book_catalog:1  # Ensure this is the tag of your built image
    container_name: book_catalog
    environment:
      DATABASE_URL: postgresql://books_inventory_user:9hNFJrnxrxlTVYcGkiVFuBEhvu5hFNoh@dpg-criiimm8ii6s73f45to0-a.oregon-postgres.render.com/books_inventory
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    networks:
      - backend

  inventory_management:
    image: inventory_management:1  # Ensure this is the tag of your built image
    container_name: inventory_management
    environment:
      DATABASE_URL: postgresql://books_inventory_user:9hNFJrnxrxlTVYcGkiVFuBEhvu5hFNoh@dpg-criiimm8ii6s73f45to0-a.oregon-postgres.render.com/books_inventory
    depends_on:
      - postgres
    ports:
      - "8001:8001"
    networks:
      - backend

networks:
  backend:

volumes:
  postgres_data:
