# Your Solution
version: '3'
services:

  book_catalog:
    build: 
      context:  ./book_catalog
      dockerfile: Dockerfile
    container_name: book_catalog
    environment:
      DATABASE_URL: postgresql://books_inventory_user:9hNFJrnxrxlTVYcGkiVFuBEhvu5hFNoh@dpg-criiimm8ii6s73f45to0-a.oregon-postgres.render.com/books_inventory
    ports:
      - "8000:8000"

  inventory_management:
    build:
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory_management
    environment:
      DATABASE_URL: postgresql://books_inventory_user:9hNFJrnxrxlTVYcGkiVFuBEhvu5hFNoh@dpg-criiimm8ii6s73f45to0-a.oregon-postgres.render.com/books_inventory
    ports:
      - "8001:8001"

